apiVersion: 1

datasources:
  - name: Zammad API
    type: grafana-simple-json-datasource
    access: proxy
    url: http://backend:8000/api/v1/grafana
    isDefault: true
    jsonData:
      httpMethod: GET
    editable: true
    version: 1

